### ISSUE TITLE
trouble getting images from repo README.md to render

### ISSUE THREAD

**Issue by ryantanaka** [pegasushub/pegasushub.github.io#2]
In the [Lung Instance Segmentation Workflow README](https://github.com/pegasus-isi/lung-instance-segmentation-workflow) I have added a diagram of the workflow using the following syntax:

```
![workflow](/img/5_proc.png)
```
This doesn't render and I see a broken link.

Similarly, if I do this
```
![workflow](https://raw.githubusercontent.com/pegasus-isi/lung-instance-segmentation-workflow/main/img/5_proc.png)
```
then the link to the image when viewed from PegasusHub becomes this: https://github.com/pegasus-isi/lung-instance-segmentation-workflow/raw/master/https://raw.githubusercontent.com/pegasus-isi/lung-instance-segmentation-workflow/main/img/5_proc.png 

Or just any random image, this doesn't render.
```
![workflow2](https://i.imgur.com/rVjiYyW.jpeg)
```
The link to the image when viewed from PegasusHub becomes this: https://github.com/pegasus-isi/lung-instance-segmentation-workflow/raw/master/https://i.imgur.com/rVjiYyW.jpeg

Regular links work correctly.

**Comment by rafaelfsilva** [comment]
@ryantanaka try to add the URL as `![workflow](img/5_proc.png)` to see if it works.

**Comment by ryantanaka** [comment]
Same issue. I see what is happening. 
The link that was generated is: https://github.com/pegasus-isi/lung-instance-segmentation-workflow/raw/master/img/5_proc.png, which is almost correct. Github renamed `master` to `main` for new repos in light of what's been happening in the past year. And so when you build the link, it actually has to be: https://github.com/pegasus-isi/lung-instance-segmentation-workflow/raw/main/img/5_proc.png.

**Comment by rafaelfsilva** [comment]
got it. I will update the code to address that. Thanks!

**Comment by papajim** [comment]
I've pushed a fix for this.
However we might want to move the Readme generation to our main processing script instead of javascript.
